version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vuln_app
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: example
      DB_NAME: vuln_app

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

volumes:
  mysql_data:
