version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vuln_app
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./server
    depends_on:
      - mysql
    ports:
      - '4000:4000'
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: example
      DB_NAME: vuln_app

  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mysql_data:
